### PR TITLE
Fixes a bug (to me) in TypeCache<T>.InitializeFromObject when initial…

### PR DESCRIPTION
**Pull request by ushenkodmitry**
…ization leaves value type arrays uninitialized

### CODE REVIEW

**Comment by ushenkodmitry** [comment]
Hello @phatboyg !
Is there something wring with the PR?

**Comment by phatboyg** [comment]
The PR is fine, I just haven't gotten around to pulling it in yet.

**Comment by ushenkodmitry** [comment]
Okay.

**Comment by ushenkodmitry** [comment]
Hello, Chris. Sorry for bother. 
Any chances for this PR to be pulled in?

**Comment by phatboyg** [comment]
I thought I had pulled it into MassTransit/GreenPipes (the official repo)

**Comment by ushenkodmitry** [comment]
It seems that you hadn't. I don't see this changes.

**Pull request merged**
