### PR TITLE
WIP for port to .net Core

### PR DESCRIPTION
**Pull request by jarroda**
For now, I left the original `*.csproj`, `.sln` and `packages.xml` files, and added new `.xproj`, `project.json` files, along with a new solution `GreenPipes.NetCore.sln`. Once the build process is implemented, those original files could be removed.

Currently, I am targeting `netstandard1.5`, however, we could drop it down to `netstandard1.3` if the usage of `ICustomAttributeProvider` was eliminated.  The only references to this interface are in `TypeExtensions.GetAttribute<T>` and `TypeExtensions.HasAttribute<T>`.  They don't appear to be used anywhere, so if we eliminated them and dropped to `netstandard1.3` it would give GreenPipes broader compatibility across platforms.

### CODE REVIEW

**Comment by phatboyg** [comment]
So, opening in Visual Studio 2015, I get this:

```
Severity    Code    Description Project File    Line    Suppression State
Error   CS0006  Metadata file 'E:\Home\GreenPipes\src\GreenPipes\bin\Debug\GreenPipes.dll' could not be found   GreenPipes.BenchmarkConsole E:\Home\GreenPipes\src\GreenPipes.BenchmarkConsole\CSC  1   Active
Error       Unable to resolve 'GreenPipes' for '.NETFramework,Version=v4.5.2'.          0   
Error       NuGet Package restore failed for project GreenPipes.Tests for 'GreenPipes '.            0   
Error       Unable to resolve 'GreenPipes' for '.NETCoreApp,Version=v1.0'.          0   
Error       Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win": { } }' to your project.json and then re-run NuGet restore.  GreenPipes          
Warning IDE0006 Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.   GreenPipes      1   Active
Error       Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win": { } }' to your project.json and then re-run NuGet restore.  GreenPipes.Tests            
Warning     Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win": { } }' to your project.json and then re-run NuGet restore.  GreenPipes.Tests            
Warning IDE0006 Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.   GreenPipes.Tests        1   Active
```

**Comment by jarroda** [comment]
Do you have Visual Studio Update 3 installed along with the .NET Core 1.0.1 - VS 2015 Tooling Preview 2 installed?  That error looks like tooling issues.  Links to those downloads are here:
https://www.microsoft.com/net/core#windows

**Comment by phatboyg** [comment]
Yes, I have both installed.

**Comment by phatboyg** [comment]
Repaired install, same issues. :(

**Comment by jarroda** [comment]
I reinstalled my tooling and it still works for me.  I had a colleague of mine try it on his machine and it loaded and built correctly for him in VS as well.  Will the project restore and build for you from the CLI using just a plain `dotnet build`?

**Comment by phatboyg** [comment]
`dotnet build` works, so I'm not sure why Visual Studio is angry.

**Comment by jarroda** [comment]
I have rebased this branch to bring it up to date with the changes in master.  Full framework and netstandard targets build and all tests pass.  

There was no develop branch when I started this port -- should these changes be rebased to develop?  I would love to get this merged in and a nuget package built so I can continue work on the MassTransit port.

**Comment by phatboyg** [comment]
I'll pull this in tonight.

**Comment by phatboyg** [comment]
Sigh, why is core such a fail. It builds on CI, but with Visual Studio it's always a train wreck.

**Comment by phatboyg** [comment]
```
Severity    Code    Description Project File    Line    Suppression State
Error       Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win": { } }' to your project.json and then re-run NuGet restore.  GreenPipes          
Error       Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win": { } }' to your project.json and then re-run NuGet restore.  GreenPipes.Tests            
Error       Unable to resolve 'GreenPipes' for '.NETCoreApp,Version=v1.0'.          0   
Error       NuGet Package restore failed for project GreenPipes.Tests for 'GreenPipes '.            0   
Error       Unable to resolve 'GreenPipes' for '.NETFramework,Version=v4.5.2'.          0   
Warning     Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win": { } }' to your project.json and then re-run NuGet restore.  GreenPipes          
Warning IDE0006 Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.   GreenPipes      1   Active
Warning     Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win": { } }' to your project.json and then re-run NuGet restore.  GreenPipes.Tests            
Warning IDE0006 Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.   GreenPipes.Tests        1   Active
```

**Comment by phatboyg** [comment]
Opening in VS2015 with Update 3 gives me this train wreck...

**Comment by jarroda** [comment]
Ok I do see the errors you're mentioning when opening `GreenPipes.sln`.  I have done my work in a new solution, `GreenPipes.NetCore.sln`.  I had assumed this would keep the original `sln` and `csproj` files unaffected until the port was complete, but apparently the presence of the `project.json` files break the old tooling.  

If you open my new solution, it should build for you in VS.  We could delete the old sln and rename the netcore sln.  Thoughts?

**Comment by phatboyg** [comment]
Oh my bad. Yeah. I'll use the new solution to build.

**Comment by phatboyg** [comment]
Okay. the .NETcore solution worked. Now, how do I run the unit test in R#? :)

And I need to update the NuGet package template to include the .NETStandard bits, trying to find a good reference on that one.

**Comment by phatboyg** [comment]
https://ci.appveyor.com/project/phatboyg/greenpipes/build/1.0.5.52

Also, created a branch on the main repository, develop-netcore with your work rebased. IF you could use this going forward to work out the final issues that would be great.

**Comment by jarroda** [comment]
I tossed a couple of more things against the wall the other night in an effort to get this build working.  It seemed to work locally, but failed on CI.  

Unless we change the FAKE build to execute `dotnet restore`, `dotnet build` etc, I'm not sure how to get this to work.  I found a little information on build a netcore project using csproj files with MsBuild, but was unable to get it to work.  In all my little projects I just invoke the `dotnet` command directly, but MT is much more complex.  The tooling is in a really sad state until this next release...

https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/target-dotnetcore-with-msbuild

**Comment by phatboyg** [comment]
I can certainly tweak the build to get what we need from the CI server, I just need to be able to work on it with Visual Studio without the project.json files getting in the way causing crazy errors!

**Comment by petriashev** [comment]
7 months later...

**Pull request closed without merging**
